name: CD
on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Echo
        run: echo CD