name: CI
on:
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Echo
        run: echo CI