name: "ci build"
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: dump github context
        run: |
          echo '${{ toJSON(github.event) }}' | jq
          echo '${{ toJSON(steps) }}' | jq
        shell: bash
#      - name: Commit files
#        run: |
#          git config --local user.email "test@test.com"
#          git config --local user.name "Test"
#          touch $RANDOM.txt
#          git add -A
#          git commit -m "Add changes"
#      - name: Push changes
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          github_token: ${{ steps.generate_token.outputs.token }}