name: release
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "version.sbt"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runt tests
        run: sleep 5
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        run: |
          git config --local user.email "slawomir.kania1@gmail.com"
          git config --local user.name "Slawomir Kania"
          featureName=$RANDOM
          touch $featureName
          git add $featureName
          git commit -m "New feature $featureName"
          git tag $featureName
      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: main
          unprotect_reviews: true
