name: release
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "version.sbt"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runt tests
        run: sleep 5
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Release
        run: |
          git config --local user.email "example@github.com"
          git config --local user.name "Example"
          version=$RANDOM
          echo $version > version.sbt
          git add -A
          git commit -m "New version $version"
          git tag $version
          git push & git push --tags
