name: release
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "version.sbt"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runt tests
        run: echo 1
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        run: echo 2