name: release
on:
  push:
    branches:
      - main
      - rulesets-flow
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "version.sbt"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runt tests
        run: sleep 5
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - name: Release
        run: |
          git config --local user.email "slawomir.kania1@gmail.com"
          git config --local user.name "Slawomir Kania"
          version=$RANDOM
          echo $version > version.sbt
          git add -A
          git commit -m "New version $version"
          git tag $version
          git push & git push --tags
